title: Bakery
email: amireynoso@gmail.com
description: Recipes with love by Ami Reynoso
url: "http://bakery.ar"
repository: "amireynoso/bakery"
baseurl: ""
twitter_username: bakery
github_username: amireynoso
plugins:
  - jekyll-feed
  - jekyll-seo-tag
permalink: /recipes/:categories/:title/
sass:
  sass_dir: _sass
  style: compressed
tag_page_layout: tag
tag_page_dir: tags
tag_permalink_style: pretty
